WindowsFormsAuth.WebApp/Models/AccountModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Web.Mvc;
using System.Web.Security;

namespace WindowsFormsAuth.WebApp.Models
{

    public class ChangePasswordModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LogOnModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email address")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

WindowsFormsAuth.WebApp/Controllers/ContaController.cs
using System.DirectoryServices.AccountManagement;
using System.Web.Mvc;
using System.Web.Security;
using System.Net;

namespace WindowsFormsAuth.WebApp.Controllers
{
    public class ContaController : Controller
    {
        public ActionResult Login(string returnUrl)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
                return !string.IsNullOrWhiteSpace(returnUrl) ? (ActionResult) Redirect(returnUrl) : RedirectToAction("Index", "Home");
            if (RequestVemDaExtranet())
                return RedirectToRoute("Default", new { action = "WebLogin", returnUrl = returnUrl });
            return RedirectToRoute("Default", new { action = "WindowsLogin", returnUrl = returnUrl });
        }

        public ActionResult WindowsLogin(string returnUrl)
        {
            var usuario = Request.ServerVariables["LOGON_USER"];

            if (string.IsNullOrWhiteSpace(usuario))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }
            FormsAuthentication.SetAuthCookie(usuario, true);
            if (!string.IsNullOrWhiteSpace(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult WebLogin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult WebLogin(string usuario, string senha, bool lembreDeMim, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (WindowsAuthenticate(usuario, senha))
                {
                    FormsAuthentication.SetAuthCookie(usuario, lembreDeMim);
                    return !string.IsNullOrWhiteSpace(returnUrl) ? (ActionResult) Redirect(returnUrl) : RedirectToAction("Index", "Home");
                }
            }
            ViewBag.Usuario = usuario;
            ViewBag.LembreDeMim = lembreDeMim;
            return View();
        }

        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        private bool RequestVemDaExtranet()
        {
            return string.Compare(Request.Url.DnsSafeHost, "localhost", true) == 0;
        }

        private static bool WindowsAuthenticate(string usuario, string senha)
        {
            using (var context = new PrincipalContext(ContextType.Machine, "nomedasuamaquina"))
            {
                return context.ValidateCredentials(usuario, senha);
            }
        }
    }
}

WindowsFormsAuth.WebApp/Controllers/HomeController.cs
using System.Net;
using System.Web.Mvc;

namespace WindowsFormsAuth.WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult Seguro()
        {
            return View();
        }
        public ActionResult TentandoPassar401()
        {
            return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
        }

      
    }
}

WindowsFormsAuth.WebApp/Views/Conta/WebLogin.cshtml
<hgroup class="title">
    <h2>Coloque seus dados abaixo.</h2>
</hgroup>

@using (Html.BeginForm()) {    
    <fieldset>
        <legend>Log in Form</legend>
        <ol>
            <li>
                <label for="usuario">Usuário</label>
                @Html.TextBox("Usuario")
            </li>
            <li>
                <label for="senha">Senha</label>
                @Html.Password("Senha")
            </li>
            <li>
                @Html.CheckBox("LembreDeMim")
                <label for="LembreDeMim" class="checkbox">Lembrar de mim?</label>                
            </li>
        </ol>
        @if (!string.IsNullOrWhiteSpace(Html.ViewBag.Usuario))
        {
            <p><span class="mensagemErro">Usuário ou senha inválida.</span></p>
        }
        <input type="submit" value="Entrar" id="Entrar" />
    </fieldset>
}

WindowsFormsAuth.WebApp/Views/Home/Index.cshtml
@section featured {
<section class="featured">
    <div class="content-wrapper">
        <hgroup class="title">
            <h1>@ViewBag.Title.</h1>
        </hgroup>
        <p>
        </p>
    </div>
</section>
}

Home page

WindowsFormsAuth.WebApp/Views/Home/Seguro.cshtml
<h2>Bem vindo à área segura!</h2>

WindowsFormsAuth.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here.", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LogOnPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Seguro", "Seguro", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
            </div>
        </footer>
    </body>
</html>

WindowsFormsAuth.WebApp/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated) {
    <p>
        Hello, @User.Identity.Name!
        @Html.ActionLink("Log Off", "LogOff", "Conta")
    </p>
} else {
    <ul>
        <li>@Html.ActionLink("Log on", "LogIn", "Conta", routeValues: null, htmlAttributes: new { id = "logonLink", data_dialog_title = "Identification" })</li>
    </ul>
}